language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email:
    - sunbergzach@gmail.com
after_success:
  - julia -e 'cd(Pkg.dir("POMDPToolbox")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
